const prod = [
  {
    heading: "Pressure Measurement",
    img: "/processInstrument/1.png",
    liItem: [
      "Absolute Pressure Transmitters ",
      "Gauge Pressure Transmitters",
      "Pneumatic Pressure Transmitters",
      "Pressure Measurement Remote Seals",
      "Differential Pressure Transmitters",
      "Multivariable      Transmitters ",
      "Pressure Measurement Accessories ",
      "Safety-Critical Transmitters",
    ],
  },
  {
    heading: "Actuator and Positioners",
    img: "/processInstrument/2.png",
    liItem: [
      "Current Pneumatic converter (I/P Converter) ",
      "Smart valve positioners",
      "Electrical Actuator",
    ],
  },
  {
    heading: "Flow Measurement",
    img: "/processInstrument/3.png",
    liItem: [
      "Coriolis Mass Flowmeters",
      "Flow  Computer  Units",
      "Thermal Mass Flowmeters",
      "Vortex & Swirl Flowmeters",
      "Electromagnetic Flowmeters",
      "Flow Measurement Accessories",
      "Wedge Flow meters",
      "Pressure Measurement Accessories",
    ],
  },
  {
    heading: "Temperature Measurement",
    img: "/processInstrument/4.png",
    liItem: [
      "Process Industry Head Thermometers ",
      "High Temperature Thermometers",
      "Sanitary Application Thermometers",
      "Cable Thermometers and Compact Thermometers",
      "Temperature Sensor Accessories ",
      "Infra-red Measurement Devices",
      "Head Mounted Temperature Transmitters ",
      "Field Mounted Temperature Transmitters",
      "Rail Mounted Temperature Transmitters",
      "Temperature Cable & Wires",
      "Pressure Measurement Accessories",
      "Safety-Critical Transmitters",
    ],
  },
  {
    heading: "Water & Industrial Analyzer",
    img: "/processInstrument/5.png",
    liItem: [
      "Ammonia Analyzers",
      "Combustion Gas Analyzers",
      "Fluoride Monitoring ",
      "Hydrazine monitors",
      "Manganese Analyzers",
      "Packaged Analyzer system",
      "Phosphate Monitors",
      "Silica Monitors",
      "Turbidity System",
      "Aluminum Analyzers",
      "Chloride Monitors",
      "Conductivity Products",
      "Dissolved Oxygen Analyzer products",
      "H2 Purity & Purge gas Monitors",
      "Iron Analyzers",
      "Nitrate Monitors",
      "ph & Redox / ORP Products",
      "Residual chlorine monitors",
      "Sodium Monitors",
    ],
  },
  {
    heading: "Universal Process Controller",
    img: "/processInstrument/6.png",
    liItem: [
      "Panel mount Controllers",
      "CM 10",
      "CM 30",
      "CM 50",
      "Field mount controller",
      "Recorder SM300",
    ],
  },
];
export default prod;
